### ISSUE TITLE
Cannot be installed on bolt-2.0.0-beta5pl4

### ISSUE THREAD

**Issue by peterboorsma** [jadwigo/SimpleForms#1]
When trying to install SimpleForms in bolt-2.0.0-beta5pl4 I get this message:

The requested extension version could not be installed. The most likely reason is that the version
requested is not compatible with this version of Bolt.

**Comment by GwendolenLynch** [comment]
This is due to you not having git installed on the server.

It will be a non issue when extensions are all tagged with release versions, very soon ;-)

**Comment by peterboorsma** [comment]
With a little bit of magic (I have no idea what I did exactly) I got it to work :)

**Comment by GwendolenLynch** [comment]
Yeah, that is the other part of the puzzle.  What is happening is the GitHub is saying that there are no zip files for master branch, then on repeat tries giving one...

**Comment by jadwigo** [comment]
this seems to work fine in the latest github clone and the 2.02 release
