### ISSUE TITLE
step by step Installation Instructions

### ISSUE THREAD

**Issue by apatkinson** [jadwigo/SimpleForms#10]
The documentation seems to lack installation instructions, am I missing something?

**Comment by apatkinson** [comment]
I clearly was, i found the back end extension install, nice.

I think I was at least expecting an installation section as usual. But I was thinking more composer.

Close issue if you like, although I still think it would be helpful for newcomers.

**Comment by jadwigo** [comment]
I'll leave it open until I've added a small line to the readme about how to install using the normal bolt extension installer
