### ISSUE TITLE
redirect_on_ok

### ISSUE THREAD

**Issue by EzeRangel** [jadwigo/SimpleForms#2]
It seems the function `simpleredirect()` doesn't work, when I try to redirect the page Bolt throws me an error that says this function doesn't exist.

![captura de pantalla 2014-12-23 a la s 17 23 02](https://cloud.githubusercontent.com/assets/1395261/5544595/67da3874-8ac8-11e4-96c6-ae382e12224c.png)

I also tryed the `simpleredirect` function imported from `Bolt\Library`but this does not work either.

Anyone knows the reason of this?

**Comment by zomars** [comment]
I also have this issue.

**Comment by jadwigo** [comment]
I see I have missed this report over the holidays - http://stackoverflow.com/questions/27767339/redirect-in-simpleforms/27788322#27788322

I guess this is a leftover from the bolt 1.6 version that needs some workaround.

I'll try to fix this as soon as possible.

**Comment by jadwigo** [comment]
nope, not yet solved

**Comment by jadwigo** [comment]
well, the simpleredirect did not do what I was expecting, I'll have to ask @GawainLynch and @bobdenotter about that

**Comment by bobdenotter** [comment]
Fixed here: https://github.com/bolt/bolt/pull/2435

**Comment by jadwigo** [comment]
Yup, redirect_on_ok works now if you use the latest checkout of bolt - it will probably in bolt 2.0.3 if you use the official releases.
