### ISSUE TITLE
Fields are not being cleared after submitting

### ISSUE THREAD

**Issue by kikocastro** [jadwigo/SimpleForms#20]
Hello, after i hit submit, the page reloads from the top and fields are not being cleared. Did that happen to you?

**Comment by jadwigo** [comment]
Do you have some more information? There should be an error message on screen somewhere?

**Comment by kikocastro** [comment]
actually i don't get any errors, the email works. the page reloads and shows the success notification. this is what i have http://52.11.80.57/contact in case you want to check the code.

**Comment by jadwigo** [comment]
could you show the simpleform.config.yml here? (please anonymize the emailaddresses first)

**Comment by kikocastro** [comment]
https://gist.github.com/5c56eb543be7be00f3d8.git

**Comment by jadwigo** [comment]
Ah, I see you are using a custom form template too - I think that your template overrides some of the logic that hides the fields when the form is sent - probably the `{% if not sent %}` block.

You could use `redirect_on_ok` in your form config to redirect the visitor to a "Thank you" page
https://github.com/jadwigo/SimpleForms/blob/master/README.md#general-settings

**Comment by kikocastro** [comment]
yeah, that was my backup plan in case i couldn't fix that on time :) i just wanted to check whether that was an issue or something i was doing wrong. i'm going to check the template. thank you for the attention Lodewijk!

**Comment by jadwigo** [comment]
Happy to help, good luck with your site :)

**Comment by jadwigo** [comment]
by the way - remember to disable `testmode` for the production site.

**Comment by kikocastro** [comment]
i'll do that! thank you :)

**Comment by kikocastro** [comment]
once i wanted to keep the form after it is submitted, my solution was to add an if statement that clears it and puts the page on the level of the form. so i removed the if not sent statement and added:

```
{% if sent %}
    <script>

        $(document).ready(function() {

            $.fn.clearForm = function() {
              return this.each(function() {
                var type = this.type, tag = this.tagName.toLowerCase();
                if (tag == 'form')
                  return $(':input',this).clearForm();
                if (type == 'text' || type == 'email' || tag == 'textarea')
                  this.value = '';
                else if (type == 'checkbox' || type == 'radio')
                  this.checked = false;
                else if (tag == 'select')
                  this.selectedIndex = -1;
              });
            };

            $("#submit-button").closest("form").clearForm();
            $(document).scrollTop( $(".contact-form").offset().top );
        });
    </script>
{% endif %}
```
