### ISSUE TITLE
Messages like "Couldn't insert data into table bolt_xx" should be in a <div>

### ISSUE THREAD

**Issue by peterboorsma** [jadwigo/SimpleForms#21]
SimpleForms uses a div class '.simpleform-message' as a container for messages.
Errors like 'Couldn't insert data into table bolt_xx' also should use that container (with an extra class, ie 'error').

**Comment by jadwigo** [comment]
unfortunately that is impossible,
stuff with the .simpleform-message is managed in twig, and this message is occuring at a time when the rest of the form is busy doing something else.

The message is removed now, if the form is not working it will only tell you so in the log, or if simpleforms is in debugmode
