### ISSUE TITLE
Integrity constraint violation: 1048 Column 'fieldname' cannot be null

### ISSUE THREAD

**Issue by peterboorsma** [jadwigo/SimpleForms#23]
Form content is not being stored in db if fields are left blank. Even if field is required: false .

I added value: leeg to the fields ('leeg' means empty). Some fields are filled with 'leeg' and others still 'null'.

See error below:

  An exception occurred while executing 'INSERT INTO bolt_menukaartitems (slug, name, email, company, contactemail, contactphone, title, productdesc, productrequirments, productdimensions, productweight, productmaterials, productspecs, productstorage, producttransport, producttransport2, productrentperiod, productcostsperiode, productpersonnelamount, productpersonnel, productpersonnelfunction, productpersonnelcosts, upload) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["watt-nox", "Peter", "x@xx.xx", "Name", "x@xx.xx", "0000000000", "test5", "adasdv dfv sdcx", "asfvs sdvsd c", "leeg", "leeg", null, null, "leeg", "leeg", null, "leeg", "leeg", null, null, null, "leeg", "No file uploaded"]:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'productmaterials' cannot be null"""
```

**Comment by jadwigo** [comment]
is this still an issue with simpleforms 1.5?

**Comment by jadwigo** [comment]
save tot table is removed from simpleforms - you have to use boltforms for that
