### ISSUE TITLE
redirect_on_ok: displays double url on redirect

### ISSUE THREAD

**Issue by melcarthus** [jadwigo/SimpleForms#27]
When setting a redirect on ok on a form, the form disappears and an double redirect message appears. Example below.

Redirecting to
/bolt/entry/page
.
/bolt/entry/page

**Comment by jadwigo** [comment]
You probably have debug mode enabled.
If you switch off debug mode you will be redirected insteadof seeing the text

**Comment by melcarthus** [comment]
This was it. Thanks for the quick reply.
