### ISSUE TITLE
Duplicate mails

### ISSUE THREAD

**Issue by Largo** [jadwigo/SimpleForms#28]
So I stumbeld upon the following weird behaviour.

Situation: I have a resource contenttype included in a template with a record.
    {% setcontent form = '/resource/content-with-the-form' %}
    {{ form.body }}
    {{ record.body }}

In the /resource/content-with-the-form I have a field body, which is allowtwig: true
and it contains:
     Some text 
    {{ simpleform('video') }}

Now somehow the simpleform is called twice on one post request, which results in the simpleform being sent twice, but only rendered once. Of course we only want one e-mail.

The temporary fix is to not include simpleform in a external record like this, otherwise no clue how to fix.

Paging @sbani, because he had a similar problem.

**Comment by jadwigo** [comment]
is the {{ form.body }} and the {{ record.body }} the same?

in that case you should only render one or the other

**Comment by Largo** [comment]
Ah no.
Sorry, I'm going to make it clearer and post my whole template.

Let's assume we have a template video.twig and use this for displaying a "video" contentype record.
My client wanted a page with her youtube videos. They are free excerpts from professional video tutorials for office software. There she wants to collect e-mail adresses.

video.twig:
    {% extends 'standard.twig' %}

```
{% block body %}
{% setcontent form = '/resource/content-with-the-form-to-collect-email-adresses' %}
{{ form.body }}
{{ record.body }}

{# Yes, I'm rendering this twice to show it below the content againt, but the problem shows up    even if this isn't called #}
{% if record.body|length > 500 %}
{{ form.body }}
{% endif %}
{% endblock %}
```

If form.body contains {{ simpleform('video') }} then it's called twice per post request. So if the user presses the send button once, it sends two e-mails. 
I solved my problem by adding simpleform('video') to video.twig, but I tought you might want to look at this problem.

**Comment by jadwigo** [comment]
In this case I would recommend to use  `{{ simpleform('video') }}` only in the template, and not in the body of a record.

I'm still not sure how it works in your template.
If the same resource is also loaded in a sidebar or somewhere else in the page, for example a footer... and even if it does not display it, the form will still be triggered when the body template is rendered, so it will be submitted twice.
