### ISSUE TITLE
inline CSS or adding tags

### ISSUE THREAD

**Issue by dev6** [jadwigo/SimpleForms#3]
Great extension for a great CMS.

Thank you to the developers.
 I wanted to add some other html or more div tags inside the <div> with the field's row. Is that possible?

I tried postfix an prefix options of this extension but that is not serving my purpose.

**Comment by jadwigo** [comment]
You could copy https://github.com/jadwigo/SimpleForms/blob/master/assets/simpleforms_form.twig and https://github.com/jadwigo/SimpleForms/blob/master/assets/simpleforms_fields.twig 

Point the simpleforms.bolt.yml to the copied version. 

And then you can modify the template for the form and the fields in the newly copied version.
