### ISSUE TITLE
Is there a way to use an AJAX call with SimpleForms?

### ISSUE THREAD

**Issue by noahjhogan** [jadwigo/SimpleForms#31]
I'm using a popup modal to display the form, but after I press submit, the page refreshes and the modal containing the form will disappear. I have to open the modal again on the refreshed page to see if there were submission errors or confirmation of success. Is there a proper way in SimpleForms to implement an AJAX call to avoid the refresh?

Much thanks! :)

**Comment by jadwigo** [comment]
Unfortunately this is something that is out of scope for this extension.

This might be a feature for boltforms - https://github.com/GawainLynch/bolt-extension-boltforms

**Comment by GwendolenLynch** [comment]
Also just to note, BoltForms will have this soon… but it is still on my TODO list.

**Comment by jadwigo** [comment]
@GawainLynch that's awesome :+1:
