### ISSUE TITLE
$this->app['log'] is deprecated

### ISSUE THREAD

**Issue by nhairic** [jadwigo/SimpleForms#35]
Hello, i use your sympathic extension, but there's a little deprecated use  ;)

DEPRECATED]: Previous message logged using deprecated log service: extensions/vendor/bolt/simpleforms/Extension.php::783

i'm on bolt 2.2.5  (use debian)

**Comment by jadwigo** [comment]
Yup...

It is already taken care of in dev-master, I need to tag a new version soon with the latest changes.

**Comment by nhairic** [comment]
Wonderfull :)

**Comment by jadwigo** [comment]
new version 1.5 is tagged so it should be fixed if you update the extension

**Comment by nhairic** [comment]
Thanks :)
