### ISSUE TITLE
Bolt 2.2.13 breaks on PHP 5.3.27 caused by SimpleForms

### ISSUE THREAD

**Issue by peterboorsma** [jadwigo/SimpleForms#42]
![screen shot 2015-10-12 at 14 08 35](https://cloud.githubusercontent.com/assets/2750653/10427669/bf0f398c-70eb-11e5-9a4b-4f6b1657cdce.png)

**Comment by jadwigo** [comment]
what version of bolt and simpleforms are you using?

**Comment by peterboorsma** [comment]
Bolt 2.2.13
SimpleForms (none cuz it didn't install) I wanted to install the latest version

**Comment by GwendolenLynch** [comment]
@jadwigo that line is one that I added in the refactor of B… I mean… SimpleForms v2.

**Comment by GwendolenLynch** [comment]
Short answer is yea, the ability to do `return (new SimpleForms($this->app))->simpleForm($formname, $with);` is a 5.4 thing… and I have my brain in 5.4+ mode now since we dropped 5.3

**Comment by jadwigo** [comment]
so something like the following should do it?

``` php
$form = new SimpleForms($this->app);
return $form->simpleForm($formname, $with);
```

**Comment by GwendolenLynch** [comment]
Yep… That, or convincing @peterboorsma to get a better host :stuck_out_tongue_winking_eye:

**Comment by peterboorsma** [comment]
The hosting is great, actually. They upgraded PHP5.3 tot 5.5 in under 30 minutes.

And... But... Butt.... The Bolt requirements says 5.3.3 will do. 
https://docs.bolt.cm/requirements

**Comment by jadwigo** [comment]
@peterboorsma yup.. 5.3.3 should do, unless :koala: forgets and writes some bleeding edge 5.4 code :grin:

**Comment by GwendolenLynch** [comment]
@peterboorsma On that. Bolt 2.2.x is our Long Term Support version, as from 2.3 the minimum requirement is 5.4.16 and Bolt v3 will require 5.5.9.

@jadwigo We should hook up Travis as the unit tests I wrote would have alerted us to this problem.

**Comment by jadwigo** [comment]
it should be fixed in dev-master
