### ISSUE TITLE
Can't override a global template

### ISSUE THREAD

**Issue by elcuro** [jadwigo/SimpleForms#49]
Thanks for the useful extension

I'm trying to override a global template in the config as mentioned in docs

```
myform:
   template: _my_custom_form_template.twig
   ...
```

but the global template is always rendered. I overlooked something?

When I look at https://github.com/jadwigo/SimpleForms/blob/master/src/SimpleForms.php#L114 the `$this->config['template']` is always the global template

**Comment by jadwigo** [comment]
Please use boltforms if you need more customization options... the simpleforms extension is not actively maintained anymore
